.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/release.yaml, .azure-pipelines/loopback-pipeline.yaml, README.md, extension.md, pipeline.build.ps1, vss-extension.json
- Update task versioning for use build number.
- Clean up CI process.
- Update extension docs.
=> Update task patch version

.azure-pipelines/jobs/release.yaml, pipeline.build.ps1, ps-project.yaml
- Disable task version update from incremented patch version.
=> Disable task version update

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, docs/features.md
- Added PR and issue templates.
- Added codeowners.
=> Add PR and issue templates

.azure-pipelines/loopback-pipeline.yaml, README.md, docs/tasks.md, tasks/ps-rule-install/powershell.ps1, tasks/ps-rule-install/powershell.ts, tasks/ps-rule-install/task.json
- Updated `ps-rule-install` module parameter to be singular.
=> Update install module parameter

README.md, docs/tasks.md, extension.md, tasks/ps-rule-assert/powershell.ps1, tasks/ps-rule-assert/powershell.ts, tasks/ps-rule-assert/task.json, tasks/ps-rule-install/powershell.ts, tasks/ps-rule-install/task.json
- Updated task docs.
- Updated task parameters.
=> Update task docs and parameters

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/release.yaml
- Add GitHub release to CI pipeline.
=> Add GitHub release to CI

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/release.yaml
- Fix publishing in CI pipeline by making stable release public.
=> Fix publishing pipeline

.azure-pipelines/jobs/release.yaml, pipeline.build.ps1
- Updated extension version variable.
=> Updated use of extension version variable

.azure-pipelines/jobs/release.yaml
- Updates to fix versioning of extension.
=> Fix extension versioning

.azure-pipelines/jobs/release.yaml, pipeline.build.ps1
- Clean up CI process after fixing extension versioning.
=> Clean up CI process after fixes

.azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version post v0.1.0 release.
Fixes #14
=> Update CI pipeline after v0.1.0 release

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/loopback-pipeline.yaml, CHANGELOG.md, README.md, docs/tasks.md, extension.md
- Fixed examples in documentation referencing outputType instead of outputFormat. #17
Fixes #17
=> Fix examples for outputFormat #17

CHANGELOG.md, pipeline.build.ps1
- Updated PSRule dependency to v0.17.0. #19
Fixes #19 
=> Update to PSRule v0.17.0

.azure-pipelines/azure-pipelines.yaml
- Update CI version to v0.3.0.
=> Update CI version post v0.2.0

README.md, extension.md
- Added extension version badge to readme.
=> Add extension version badge

CHANGELOG.md, pipeline.build.ps1
- General improvements:
- Updated to PSRule v0.18.0. #24
Fixes #24 
=> Updated to PSRule v0.18.0 #24

.azure-pipelines/azure-pipelines.yaml
- Update CI version to v0.4.0.
=> Update CI post v0.3.0

CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Updated to PSRule v0.18.1. #28
=> Updated to PSRule v0.18.1 #28

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/loopback-pipeline.yaml, .github/PULL_REQUEST_TEMPLATE.md, README.md, extension.md, package.json, tasks/ps-rule-assert/task.json, tasks/ps-rule-install/task.json
- Update references for default branch to main.
=> Rename default branch to main

CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Updated to PSRule v0.19.0. [#31](https://github.com/microsoft/PSRule-pipelines/issues/31)
=> Update to PSRule v0.19.0 #31

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md
- Updated CI pipeline version to v0.5.0.
=> Update CI version post v0.4.0

tasks/ps-rule-assert/powershell.ps1
- Fix file target name not binding to display name.
=> Fixed file target name not binding to display name

CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Updated to PSRule v0.20.0. #54
Fixes #54 
=> Updated to PSRule v0.20.0 #54

CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Updated to PSRule v0.21.0. #72 
Fixes #72 
=> Update PSRule dependency to v0.21.0 #72

.github/workflows/analyze.yaml, .ps-rule/OpenSource.Rule.ps1
- Added validation of repository with GitHub Actions workflow.
Fixes #92
=> Add repository validation #92

CHANGELOG.md, docs/upgrade-notes.md, pipeline.build.ps1, ps-project.yaml
- Engineering:
- Updated to PSRule v1.0.0. #82 
Fixes #82 
=> Bump PSRule to v1 #82

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Bump PSRule dependency to v1.0.1 #106
Fixes #106
=> Bump PSRule dependency to v1.0.1 #106

CHANGELOG.md, docs/tasks.md, tasks/ps-rule-assert/powershell.ps1, tasks/ps-rule-assert/task.json
- Added support for markdown output format. #114
Fixes #114 
=> Added support for markdown output format #114

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Bump PSRule dependency to v1.1.0. #128
Fixes #128
=> Bump PSRule dependency to v1.1.0 #128

pipeline.build.ps1, ps-project.yaml
- Fix referenced PSRule versions in CI.
=> Update PSRule version in CI

.azure-pipelines/azure-pipelines.yaml, pipeline.build.ps1
- Bumped CI version to v1.0.0.
=> Updated CI pipeline version

README.md, SUPPORT.md
- Added/ updated support information.
=> Added SUPPORT.md

package-lock.json, package.json
- Remove reference for `tfx-cli`.
=> Cleanup tfx-cli dev dependency

CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Bump PSRule dependency to v1.4.0. #163
Fixes #163 
=> Bump PSRule dependency to v1.4.0 #163

.azure-pipelines/azure-pipelines.yaml, .github/workflows/analyze.yaml
=> Fix release pipeline

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md
- Fix change log and bump CI pipeline version.
=> Update change log

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, pipeline.build.ps1, ps-project.yaml
- Bump PSRule dependency to v1.5.0.
Fixes #184
=> Bump PSRule dependency to v1.5.0 #184

CHANGELOG.md
- Bump azure-pipelines-task-lib to 3.1.5. #188
=> Bump azure-pipelines-task-lib to 3.1.5 #188

tasks/ps-rule-assert/powershell.ps1, tasks/ps-rule-assert/powershell.ts
- Fix issues with check for conventions that prevents binding.
=> Fix issue binding conventions

CHANGELOG.md
- Update change log with dependabot updates.
=> Add updates to change log

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/release.yaml
- Bumped CI pipeline to v1.3.0.
=> Bump CI pipeline versions

.github/workflows/stale.yaml
- Added management for stale issues.
=> Added stale issue cleanup

vss-extension.json
=> Fix typo in manifest

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md
What's changed since v1.4.0:
- Engineering:
- Update extension icon to the latest version. #279
- Update node execution handler to Node 10. #265
- Added `ps-rule-assert@1` task that uses Node 10 extension handler.
- Added `ps-rule-install@1` task that uses Node 10 extension handler.
- Please upgrade your pipelines to the latest task versions to avoid issues.
- Added warning to older task versions to ensure they are upgraded.
- Bump PSRule dependency to v1.11.0. #278
- See the [change log](https://github.com/microsoft/PSRule/blob/main/docs/CHANGELOG-v1.md#v1110).
=> Release v1.5.0

package-lock.json
- Bumped shelljs to latest version v0.8.5.
=> Bump shelljs

.eslintignore, .eslintrc.json, package-lock.json, package.json
- Switch to eslint instead of tslint.
=> Switch to eslint

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/loopback-pipeline.yaml, CHANGELOG.md, package-lock.json, tasks/ps-rule-assertV2/powershell.ps1, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-assertV2/task.json, tasks/ps-rule-assertV2/tsconfig.json, tasks/ps-rule-installV2/powershell.ps1, tasks/ps-rule-installV2/powershell.ts, tasks/ps-rule-installV2/task.json, tasks/ps-rule-installV2/tsconfig.json, vss-extension.json
- Preparing for PSRule v2 support with v2 tasks.
- Added support for SARIF output format.
Fixes #312 
Fixes #315 
=> Prepare for PSRule v2 #312

.github/workflows/analyze.yaml, tasks/ps-rule-assertV0/powershell.ts, tasks/ps-rule-assertV1/powershell.ts, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-installV0/powershell.ts, tasks/ps-rule-installV1/powershell.ts, tasks/ps-rule-installV2/powershell.ts
- Added CodeQL scans from GitHub in addition to existing security scans.
=> Add CodeQL scans in GitHub

.github/workflows/dependencies.yaml, modules.json, ps-rule.yaml, scripts/dependencies.psm1
- Add workflow to update repo dependencies.
=> Add repo dependency updates

CHANGELOG.md, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-installV2/powershell.ts, vss-extension.json
- Fixed failure loading VstsTaskSdk.
Fixes #361
=> Fixed failure loading VstsTaskSdk #361

CHANGELOG.md, tasks/ps-rule-assertV2/powershell.ps1
- Fixed handling of unset path.
Fixes #363
=> Fix path handling #363

tasks/ps-rule-assertV2/task.json
=> Fix path padding #363

tasks/ps-rule-assertV2/powershell.ps1
- Fixes additional path prefix. #363 
=> Fixes path prefix #363

CHANGELOG.md, tasks/ps-rule-assertV0/task.json, tasks/ps-rule-assertV2/task.json, tasks/ps-rule-installV0/task.json, tasks/ps-rule-installV2/task.json
- Flagged v0 tasks as deprecated.
Fixes #399 
=> Updated task flags #399

.azure-pipelines/azure-pipelines.yaml, pipeline.build.ps1
- Fix CI pipeline for v2 release.
=> Update CI for release

CHANGELOG.md, modules.json, vss-extension.json
- Bump PowerShell dependencies.
=> Bump PowerShell dependencies

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/dependencies.yaml, extension.md
=> Fix dependency workflow

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/release.yaml
=> Bump CI version and tools

CHANGELOG.md, pipeline.build.ps1, tasks/ps-rule-assertV2/powershell.ps1, vss-extension.json
- Improved display of extension version in output.
Fixes #386 
=> Improved display of extension version #386

tasks/ps-rule-assertV2/powershell.ps1
- Fixes for loading task version.
=> Fix version information file loading

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md
What's changed since v2.1.0:
- General improvements:
- Improved display of extension version in output by @BernieWhite.
[#386](https://github.com/microsoft/PSRule-pipelines/issues/386)
- Engineering:
- Bump PSRule to v2.2.0.
[#467](https://github.com/microsoft/PSRule-pipelines/pull/467)
- See the [change log](https://microsoft.github.io/PSRule/latest/CHANGELOG-v2/#v220)
=> Release v2.2.0

.azure-pipelines/azure-pipelines.yaml
=> Bump CI version

CHANGELOG.md
What's changed since v2.4.1:
- Engineering:
- Bump PSRule to v2.4.2.
[#553](https://github.com/microsoft/PSRule-pipelines/pull/553)
- See the [change log](https://microsoft.github.io/PSRule/v2/CHANGELOG-v2/#v242)
=> Release v2.4.2

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md, README.md, docs/tasks.md, extension.md, tasks/ps-rule-assertV2/powershell.ps1, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-assertV2/task.json
- Added outcome filtering parameter.
Fixes #570 
=> Added outcome filtering #570

.azure-pipelines/azure-pipelines.yaml, pipeline.build.ps1
=> Update package versioning

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md, pipeline.build.ps1, tasks/ps-rule-assertV2/powershell.ps1
- Fixed stale task versioning.
Fixes #589 
=> Fixes stale task versioning #589

CHANGELOG.md
What's changed since v2.5.1:
- Engineering:
- Bump PSRule to v2.5.3.
[#581](https://github.com/microsoft/PSRule-pipelines/pull/581)
- See the [change log](https://microsoft.github.io/PSRule/v2/CHANGELOG-v2/#v253)
- Bug fixes:
- Fixed stale task versioning by @BernieWhite.
[#589](https://github.com/microsoft/PSRule-pipelines/issues/589)
=> Release v2.5.2

extension.md
Update extension instructions on marketplace.
=> Update extension instructions

CHANGELOG.md
What's changed since v2.5.2:
- Engineering:
- Bump PSRule to v2.6.0.
[#606](https://github.com/microsoft/PSRule-pipelines/pull/606)
- See the [change log](https://microsoft.github.io/PSRule/v2/CHANGELOG-v2/#v260)
- Bump typescript to v4.9.3.
[#603](https://github.com/microsoft/PSRule-pipelines/pull/603)
=> Release v2.6.0

.azure-pipelines/azure-pipelines.yaml
=> Bump pipeline version

.azure-pipelines/jobs/release.yaml, README.md
=> Fix release

CHANGELOG.md, tasks/ps-rule-assertV2/task.json, tasks/ps-rule-installV2/task.json
- Updated V2 tasks to support Node 16.
Fixes #693 
=> Updated V2 tasks to support Node 16 #693

pipeline.build.ps1
=> Fix task versioning

package-lock.json, package.json, tasks/ps-rule-assertV0/powershell.ts, tasks/ps-rule-assertV1/powershell.ts, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-installV0/powershell.ts, tasks/ps-rule-installV1/powershell.ts, tasks/ps-rule-installV2/powershell.ts
=> Updated module refs

.azure-pipelines/azure-pipelines.yaml, build.mjs, extension.config.js, package-lock.json, package.json, pipeline.build.ps1, tasks/ps-rule-assertV0/powershell.ts, tasks/ps-rule-assertV1/powershell.ts, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-installV0/powershell.ts, tasks/ps-rule-installV1/powershell.ts, tasks/ps-rule-installV2/powershell.ts
- Fixes for extension bundling.
=> Fix bundling

.azure-pipelines/azure-pipelines.yaml, .azure-pipelines/jobs/release.yaml, pipeline.build.ps1
- Prepare canary for official Microsoft release.
Related to #513 
=> Bump versions

.azure-pipelines/azure-pipelines.yaml, CHANGELOG.md, docs/tasks.md, tasks/ps-rule-assertV2/powershell.ps1, tasks/ps-rule-assertV2/powershell.ts, tasks/ps-rule-assertV2/task.json
- Added job summary.
Fixes #724
=> Add job summary

docs/tasks.md, tasks/ps-rule-assertV2/powershell.ps1
- Fix clean up of summary file.
=> Fix summary clean up

pipeline.build.ps1
=> Fix task version numeric

tasks/ps-rule-assertV2/powershell.ps1
- Join full path to job summary.
=> Join full path to job summary

CHANGELOG.md, tasks/ps-rule-assertV2/powershell.ps1
- Fixed summary with job summary.
Fixes #750 
=> Fixes summary with job summary #750

CHANGELOG.md, extension.config.js, modules.json
=> Bump PSRule to v2.8.0

CHANGELOG.md, extension.config.js, modules.json
- Engineering:
- Bump PSRule to v2.8.1.
- See the [change log](https://microsoft.github.io/PSRule/v2/CHANGELOG-v2/#v281)
=> Release v2.8.1

CHANGELOG.md, extension.config.js, modules.json
- Bump PSRule to v2.9.0.
- See the [change log](https://microsoft.github.io/PSRule/v2/CHANGELOG-v2/#v290)
=> Dependencies bump

CHANGELOG.md
What's changed since v2.8.1:
- Engineering:
- Bump PSRule to v2.9.0.
- See the [change log](https://microsoft.github.io/PSRule/v2/CHANGELOG-v2/#v290)
- Bump typescript to v5.1.3.
[#806](https://github.com/microsoft/PSRule-pipelines/pull/806)
=> Release v2.9.0

.github/ISSUE_TEMPLATE/bug_report.md, .github/dependabot.yml, .github/workflows/analyze.yaml, .github/workflows/build.yaml, .github/workflows/dependencies.yaml, .github/workflows/stale.yaml, .vscode/settings.json, package-lock.json
Additional updates to CI process.
=> Updates to CI process

.azure-pipelines/azure-pipelines.yaml
=> Clean up CI trigger

CHANGELOG.md, package-lock.json
Bump change log and package lock dependencies.
=> Bump change log and lock

.github/dependabot.yml
=> Group linting dependencies

.github/workflows/analyze.yaml, .github/workflows/build.yaml, .github/workflows/dependencies.yaml, .github/workflows/stale.yaml, package-lock.json
Pin dependencies in workflows and ensure that default permissions are set.
=> Pin workflow dependencies
